AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Processing batch system messages on an SQS queue with Lambda
Resources:
  BatchSQSQueueFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./index.js
      Handler: index.handler
      Runtime: nodejs8.10
      Events:
        BatchSQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt BatchSqsQueue.Arn
            BatchSize: 10

  BatchSqsQueue:
    Type: AWS::SQS::Queue
