AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Processing batch system messages on an SQS queue with Lambda
Parameters:
  CompanyParameter:
    Type: String
    Description: Company name
    AllowedPattern: "[A-Za-z0-9]+"
    ConstraintDescription: Company name must only contain uppercase and lowercase letters and numbers
Resources:
  BatchSQSQueueFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./index.js
      Description: process the batch data messages
      FunctionName: batch-sqs-queue-process
      Handler: index.handler
      Runtime: nodejs8.10
      Events:
        BatchSQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt BatchSqsQueue.Arn
            BatchSize: 10
  BatchSqsPublisher:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub batch-sqs-queue-publisher-${CompanyParameter}
      Path: "/"
      Policies:
      - PolicyName: giveaccesstoqueueonly
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - sqs:*
            Resource:
            - !GetAtt BatchSqsQueue.Arn
          - Effect: Deny
            Action:
            - sqs:*
            NotResource:
            - !GetAtt BatchSqsQueue.Arn 
  BatchSqsPublisherAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:    
      UserName: 
        !Ref BatchSqsPublisher
  BatchSqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub batch-sqs-queue-${CompanyParameter}
Outputs:      
  PublisherAccessKey:
    Description: batch sqs queue publisher iam access key
    Value:
      !Ref BatchSqsPublisherAccessKey        
  PublisherSecretKey:
    Description: batch sqs queue publisher iam secret key
    Value: !GetAtt BatchSqsPublisherAccessKey.SecretAccessKey